### ISSUE TITLE
Not able to deploy this component

### ISSUE THREAD

**Issue by wuetz** [awslabs/aws-greengrass-labs-secretsmanagerclient#1]
Hello all,

i'm triing to deploy this as a Greengrass component via IoT Greengrass deployments. As I already observed this is not part of the "Greengrass software catalog" e.g. `gdk component list --repository` is not showing it. 
So i was wondering how I will be able to create a component? Is there any documentation about it?

**Comment by sfph** [comment]
> 

Hi there - I have been adding components by manually adding the recipe.yaml file from 'AWS IOT' 'Greengrass Devices' 'Components' 'My Components' 'Create Component'

However, this one fails for me because 'secrets.jar' isn't a proper URI.  I tried creating an S3 bucket and putting that path there, but then the whole deployment fails since secrets.jar can't be found in the S3 bucket.  No idea where that's supposed to come from; I was rather hoping it would come from this component.  :) (Values "", or "/greengrass/etc etc" also failed).  I haven't found any references to this whole chain of components in the wild, so I'm wondering if we're the first two people to ever try it..  

Edit: tried adding with gdk component build/publish and it still chokes on secrets.jar and I still have no idea what to put in its place.  There's a s3 bucket associated with the SecretManager component in my deployment, but that doesn't get recognized as a valid s3 uri either..

**Comment by massi-ang** [comment]
Hi,

thanks for your interest in using this component. I realize the README is not clear enough in regards on how to upload those component. We will work to provide clearer instructions. In the meanwhile please have a look at the instructions provided in [BUILD.md](https://github.com/awslabs/aws-greengrass-labs-secretsmanagerclient/blob/main/BUILD.md)
